FROM registry.redhat.io/rhel9/rhel-bootc:9.8

RUN dnf -y install \
        vim \
        buildah \
        skopeo \
        podman 

RUN dnf config-manager --set-enabled codeready-builder-for-rhel-9-x86_64-rpms && \
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    mv /etc/selinux /etc/selinux.tmp && \
    dnf install -y htop && \
    dnf clean all && \
    mv /etc/selinux.tmp /etc/selinux


RUN useradd ogren -p '$6$7YSd3WNXIW2wVHrQ$I0ObMnnaZ3QsQL56wh0btjqLyUTZRQxc6dknks1nzGzrSKifNGFMeJPAeS9N8/WXlMpHsIGY5JWc.2VkKoAlW0'
COPY etc/sudoers /etc/sudoers
